FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
COPY src/ .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3008"]
